### ISSUE TITLE
Changing name of the repo

### ISSUE THREAD

**Issue by pariterre** [conda-forge/biorbd-viz-feedstock#20]
@conda-forge-admin 
Hi! 
The main repo changed name from `biorbd-viz` to `bioviz`. How can I update this repo (and the push toward Anaconda) to comply to this?
Thanks!

**Comment by pariterre** [comment]
@conda-forge/staged-recipes

**Comment by nehaljwani** [comment]
cc @conda-forge/core

**Comment by beckermr** [comment]
If you really want to change the name of the repo, then submit a new recipe to staged recipes and we can archive this one. 

If you only need to change the name of the package, you can do that in the meta.yaml and that will work just fine.

**Comment by pariterre** [comment]
@beckermr 
If I change the name of the package in meta.yaml, will this change the uploaded package name as well?
I mean, to install it, will ones has to type : `conda install new_package_name -cconda-forge` or `conda install old_package_name -cconda-forge` (which would contain the new name package so in Python `import new_package_name`)?

Thanks for your fast answer!

**Comment by beckermr** [comment]
> If I change the name of the package in meta.yaml, will this change the uploaded package name as well?

Yes if you change the name in the metal.yaml, then you need to use the new name to install it.
